added checksum verification to stashaway script

diff --git a/convenience/stashaway b/convenience/stashaway
--- a/convenience/stashaway
+++ b/convenience/stashaway
@@ -1,32 +1,40 @@
 #!/usr/bin/env bash
 #
-# Archive, compress, and compute checksums.
+# Archive and compress the immediate subdirectories within
+# a specified directory, provided as a script argument, and
+# compute the checksums for both the resulting compressed
+# archives and the files within each immediate subdirectory.
 
 set -o nounset -o errexit -o noclobber -o pipefail
 
 if [ "${#}" -eq 0 ]; then
-    echo "Usage: ${0} <directory-path>"
+    echo "Usage: ${0} DIRECTORY"
     exit 0
 elif [ "${#}" -ne 1 ]; then
     echo "Expected 1 argument, got ${#}" >&2
     exit 1
 fi
 
-if ! BASE_DIR="$(realpath --quiet --canonicalize-existing "${1}")"; then
-    echo "'${BASE_DIR}' is not a valid path." >&2
+if ! BASE_DIR="$(realpath --canonicalize-existing "${1}")"; then
+    echo "Argument is not a valid path: ${1}" >&2
     exit 1
 fi
 
 readonly BASE_DIR
 
 if [ ! -d "${BASE_DIR}" ] || [ -L "${BASE_DIR}" ]; then
-    echo "'${BASE_DIR}' must be a regular directory." >&2
+    echo "Argument must be a regular directory: ${BASE_DIR}" >&2
     exit 1
 fi
 
 readonly STASH_CHECKSUMS="${BASE_DIR}/SHA256SUMS"
 
-readonly EXPR='s#^\(.\{64\}\)\(\s\{2\}\)'"${BASE_DIR}"'/\(.*\)#\1\2\3#p'
+if [ -e "${STASH_CHECKSUMS}" ]; then
+    echo "Checksums file already exists: ${STASH_CHECKSUMS}" >&2
+    exit 1
+fi
+
+readonly EXPR='s#^\(.\{64\}\)\(\s\{2\}\)'"${BASE_DIR}"'/\(.*\)$#\1\2\3#p'
 
 echo "Base directory: ${BASE_DIR}"
 
@@ -34,22 +42,22 @@ while read -r dir_path; do
     dir_name="$(basename "${dir_path}")"
     stash_dir="${BASE_DIR}/.${dir_name}.stash"
 
+    echo -e "\nCurrent subdirectory: ${dir_name}"
+
     if [ -d "${stash_dir}" ] || ! mkdir "${stash_dir}"; then
         echo "Unable to create directory: ${stash_dir}" >&2
         exit 1
     fi
 
-    echo -e "\nCurrent subdirectory: ${dir_name}"
-
     echo "Computing checksums of files in the current subdirectory..."
 
-    find "${dir_path}" -type f -exec sha256sum {} \; \
+    find "${dir_path}" -type f -exec sha256sum {} + \
         | sed -n "${EXPR}" > "${stash_dir}/${dir_name}.sha256"
-    
-    # compressed archive output
-    comparch="${stash_dir}/${dir_name}.tar.bz2"
 
     echo "Archiving and compressing current subdirectory..."
+
+    # compressed archive output
+    comparch="${stash_dir}/${dir_name}.tar.bz2"
 
     tar --create \
         --backup=numbered \
@@ -92,4 +100,21 @@ done < <(find "${BASE_DIR}" -mindepth 1 -maxdepth 1 -type d)
 
 chmod 444 "${STASH_CHECKSUMS}"
 
+echo "Verifying stash files checksums..."
+
+if ! find "$(dirname "${STASH_CHECKSUMS}")" -name "$(basename "${STASH_CHECKSUMS}")" -type f \
+    -execdir sha256sum --check --quiet --status --strict {} +; then
+    echo "Stash files failed checksum varification." >&2
+    exit 1
+fi
+
+echo "Verifying stash items checksums..."
+
+if ! find "${BASE_DIR}" -path "${BASE_DIR}/.*.stash/*.sha256" -type f \
+    -execdir sha256sum --check --quiet --status --strict {} +; then
+    echo "Failed checksum varification." >&2
+    exit 1
+fi
+
 echo -e "\nEverything has been successfully stashed away."
+
